[package]
name = "web_scrapper_project"
version = "0.1.0"
edition = "2024"

[dependencies]

tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
scraper = "0.18.1"
serde_json = "1.0"
dotenv = "0.15"
